name: Publish

on:
  workflow_dispatch:
    inputs:
      plugin_version:
        description: 'New plugin version, e.g. "1.5"'
        required: true
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Gradle build & Publish
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          PLUGIN_VERSION: ${{ github.event.inputs.plugin_version }}
        run: |
          ./gradlew build
          ./gradlew publishPlugins
          echo "Plugin should now be available at https://plugins.gradle.org/plugin/io.invertase.gradle.build/$PLUGIN_VERSION"
